### PR TITLE
Update path to jacktrip binary

### PR DESCRIPTION
**Pull request by madwort**
* 1.3 installer put its in a different place by default!

### CODE REVIEW

**Comment by madwort** [comment]
just tested this, I think it works now - have some test sessions tmrw, if that goes ok will merge this & release 1.1.1

**Review by sandreae — APPROVED** [review]
Just tested this and it seemed to work fine. Connected with one client successfully, got audio back, stream worked. :+1:

**Comment by madwort** [comment]
Great - merged - could release 1.1.1?

**Comment by madwort** [comment]
Actually - I'm going to release it as 2.0, because it's dropping jt 1.2 compat

**Pull request merged**
