### PR TITLE
Change filename and path for recordings

### PR DESCRIPTION
**Pull request by sandreae**
I'm starting to upload the recordings to our cloud storage, a couple of small changes here:

- store recordings in dedicated folder `home/sam/recordings/audio`
- name the files with date and time strings `2020_11_05_1749_darckice-01`

### CODE REVIEW

**Comment by sandreae** [comment]
I should change the file path to `~/recordings/audio/`

**Review by madwort — CHANGES_REQUESTED** [review]
The code update looks good, but there's a much better way of doing the test - you can use https://github.com/ktosiek/pytest-freezegun to get python to pretend it's a specific date & time, then you can run your code without the mock

**Comment by madwort** [comment]
(ping me if you get stuck)

**Comment by sandreae** [comment]
Ok, thanks, will get on it.

**Comment by madwort** [comment]
(it's dead easy, although if you prefer we could merge this & I could file a PR to use freezegun?)

**Comment by sandreae** [comment]
> (it's dead easy, although if you prefer we could merge this & I could file a PR to change to freezegun?)

Yeh, it'd be good to just merge this and improve the tests later if that's ok...

**Review by madwort — APPROVED** [review]

**Pull request merged**
