### PR TITLE
Make compatible with JackTrip v1.2 and v1.3

### PR DESCRIPTION
**Pull request by sandreae**

### CODE REVIEW

**Comment by madwort** [comment]
any chance of a test or two?

**Comment by sandreae** [comment]
yep!

**Comment by sandreae** [comment]
Not the most beautiful test... but you get the point....

**Comment by madwort** [comment]
ah! yeah! I was actually thinking about tests to verify other bits of the codebase are working, like https://github.com/noiseorchestra/jacktrip_pypatcher/blob/trunk/test_jack_client_patching.py#L7-L10 but good to check this too - bit of an awkward one, right?

**Comment by sandreae** [comment]
Ah, ok, gotcha. I actually couldn't find any reference to the ".." part of the JackTrip client names in the rest of the code. Think we're just checking for "receive_1" to identify JT clients, but I can do a few tests anyway, you're right, there may be unknown unknowns!

**Comment by madwort** [comment]
> unknown unknowns 
😆

**Comment by sandreae** [comment]
:sparkles:

**Review by madwort — APPROVED** [review]
yep looks good

**Pull request merged**
