### PR TITLE
Refactor 2 & 3 client patching

### PR DESCRIPTION
**Pull request by sandreae**
This would be the first step in moving all patching logic for 2 -> 11 clients into `jack_client_patching`. Sure there are a few different approaches to this though, how does this look as a basis? After this we could implement logic for the `darkice` connections. ~~Also I imagine refactoring the different connection type methods (client -> ladspa, ladspa -> client, ladspa -> darkice etc..) into one method with a switch and connection_type keys.~~ <-- for another time if at all....

~~BLOCKED: merge #61 first~~

### CODE REVIEW

**Comment by sandreae** [comment]
(sorry, the commits are a bit confusing, the two associated with this PR are https://github.com/noiseorchestra/jacktrip_pypatcher/pull/62/commits/21e5bd810b9537ff633f0d8c3030d44ff25051cb & https://github.com/noiseorchestra/jacktrip_pypatcher/pull/62/commits/16cf0b10d0e5f257f2aac7115a79fc1c217e4d57)

**Comment by madwort** [comment]
ah, I see, this includes the content of #61 as well as the stuff for this PR? let's block this one temporarily, merge #61 then rebase this one?

**Comment by sandreae** [comment]
tbh I'm not 100% sure about this approach, feels like we're already starting to duplicate logic with the `set_ladspa_connection` and `connect_from_ladspa` methods. Maybe the `set` methods which build up our testable list of connections should be where the `(receive + ":receive_.*", ladspa + ":Input.*")` logic happens, then we don't need to specify what type of connection is being made in the final `make_all_connections` run? We just run the whole list through `jackClient`.

Or some other approach... ;-p

**Comment by sandreae** [comment]
Closing this as we're gunna proceed with a different method : https://github.com/noiseorchestra/jacktrip_pypatcher/pull/64

**Pull request closed without merging**
